### ISSUE TITLE
Errors after importing HoloToolKit-Unity-v1.5.7.0.unitypackage

### ISSUE THREAD

**Issue by BenjaminAbshire** [Microsoft/HoloToolkit-Unity#684]
I downloaded the latest package (see header) today and after importing into a new Unity 5.5.2f1 project I get the three errors below. I got the package from Master Branch/HoloToolkit-Unity/External/Unitypackages/.

Assets/HoloToolkit/Build/Editor/BuildSLNUtilities.cs(174,37): error CS1501: No overload for method `SwitchActiveBuildTarget' takes `2' arguments

Assets/HoloToolkit/Build/Editor/BuildSLNUtilities.cs(248,41): error CS1501: No overload for method `SwitchActiveBuildTarget' takes `2' arguments

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs(207,41): error CS1501: No overload for method `SwitchActiveBuildTarget' takes `2' arguments

I'm not sure how to fix this. You assistance is greatly appreciated.

**Comment by thebanjomatic** [comment]
@BenjaminAbshire The corresponding supported version of Unity for 1.5.7 is Unity 5.6.1f1. This is likely the source of the errors.

@StephenHodgson There appears to be a typo in the release notes for 1.5.7... 5.5.61f1 => 5.6.1f1.
> Latest release of the HoloToolkit for Unity 5.5.61f1

**Comment by BenjaminAbshire** [comment]
Strange. HoloToolKit-Unity 1.5.6 works in Unity 5.5.2f1 just fine. 1.5.7 does not. Why would the newer version (1.5.7) require an older version of Unity (5.5.6f1)?

**Comment by thebanjomatic** [comment]
@BenjaminAbshire It doesn't... 5.5.6 isn't a thing that was a typo in the release notes. The current supported version went up to 5.6.1f1.

HTK 1.5.5 => Unity 5.5.0f3
HTK 1.5.6 => Unity 5.5.2f1
HTK 1.5.7 => Unity 5.6.1f1

**Comment by StephenHodgson** [comment]
Thanks for the typo catch. I'll update right away.

**Comment by BenjaminAbshire** [comment]
Thanks for clarifying. I misunderstood your previous reply because I didn't realize a newer version of Unity was available. The version break down you provided cleared it up nicely. I have downloaded the latest Unity version (1.5.6f1) and imported HTK 1.5.7. I am happy to report that all is working correctly now and no strange errors after import. Thanks for your help.
