### ISSUE TITLE
⚠️ HoloToolkit no longer supports Unity 5.4.0f1-HTP

### ISSUE THREAD

**Issue by riverar** [Microsoft/HoloToolkit-Unity#497]
I maintain https://holotoolkit.download and was running builds on Unity 5.4.0f1-HTP. Just a heads up that a recent change (https://github.com/Microsoft/HoloToolkit-Unity/commit/261802b9767fc3ee77e1e271da4f68235771fdce#diff-d7c8f5f8602786a2bff59bc9835eccf9R219) broke compatibility. It's not clear if this project is attempting to maintain Unity back compat. so no patch submitted at this time.

I plan on upgrading Unity on the server.

```
-----CompilerOutput:-stderr----------
Assets/HoloToolkit/Sharing/Scripts/Spawning/PrefabSpawnManager.cs(219,24):
error CS0266: Cannot implicitly convert type `UnityEngine.Object' to `UnityEngine.GameObject'.
An explicit conversion exists (are you missing a cast?)
-----EndCompilerOutput---------------
```

**Comment by S-Hodgson-MMOARgames** [comment]
I don't think it would be too difficult to revert that line, sense it was a trivial change.

Sorry about that @riverar. I'll have the fix in tomorrow.

**Comment by thebanjomatic** [comment]
I could be wrong, but I don't think there is any expectation that anything beyond the [1.5.4.0 release tag](https://github.com/Microsoft/HoloToolkit-Unity/releases/tag/v1.5.4.0) is compatible with Unity 5.4. The with the current master branch targeting Unity 5.5 exclusively.

**Comment by riverar** [comment]
I upgraded my build box so you don't need to reinsert the cast. We might want to instead note in the Readme that Unity `[v.current]` is required.

**Comment by HodgsonSDAS** [comment]
It is noted in the readme.

**Comment by riverar** [comment]
Current Unity Editor Project Version isn't quite the same as Required Unity Editor Version. Suggest revisiting this. @NeerajW @HodgsonSDAS

**Comment by HodgsonSDAS** [comment]
It's not part of https://github.com/Microsoft/HoloToolkit-Unity/pull/496
